#!/bin/bash
###########
# Genboot #
###########
#
# A framework for building boot environments
############################################
#
# Example usage in clean qemu environment
#
# $ qemu-kvm \
# $     -m 10G \
# $     -smp 6 \
# $     -kernel vmlinuz \
# $     -initrd initramfs \
# $     -net nic,model=virtio \
# $     -net user \
# $     -nographic \
# $     -append console=ttyS0

# Which is ofcourse, useless without me supplying 
# the vmlinuz and initramfs files.
# Creation of the initramfs is sill a manual task
# It does some things atypical to a standard distro initramfs.
#   - Only a kernel and initramfs are supplied to qemu, there
#     is no stateful disk image.
#   - The root= kernel cmdline is set inside the initramfs,
#     not supplied to qemu's "-append".
#   - The VM uses a lot of RAM. All writes are directed
#     towards an RAM backed AUFS rootfs.
#   - QEMU User networking provides a crippeled network
#     environment, sufficient enough for TCP to download
#     the portage tree and distfiles.
#   - No other special networking needs to be made. Qemu can be run
#     as a non-privilaged user.
#   - While the kernel is fairly standard
#     (sys-kernel/aufs-sources), however, network drivers and other
#     config is taylored for my environment.
#   - Kernel modules insude the initramfs are coupled to
#     the kernel version. (In theory, the initramfs could be
#     bundled into the kernel too)
#   - The initramfs is at least as big as any generated
#     tarball since the initramfs will effectively perform
#     a stage3 install during the boot process. It is a neat
#     chicken/egg problem that requires the stage3 to build the
#     initramfs, and the qemu/kernel/initramfs to (cleanly) build
#     the stage tarball.
#   - My custom dracut module is not documented (or described) here.

# Once the VM has booted, root login is permitted (without password)

# Set SYNC and GENTOO_MIRRORS variables in /etc/portage/make.conf first.
set -x
emerge --sync
eix-update

# Enable ssh, not sure why the ebuild didn't set these directories properly
chown root /var/empty
chmod 755 /var/empty
systemctl start sshd

# Run /usr/bin/passwd to set a password and enable remote logins
# (optional) passwd

set -e
# If, for some reason, binutils is not installed with $ROOT/usr/portage/profiles
# programs like ar and ld can't be found.
# make the symlinks by calling binutils-config when a real portage tree exists
ar -V || {
    source /etc/env.d/binutils/$(gcc -dumpmachine)-*
    binutils-config "$TARGET-$VER" && env-update
    source /etc/profile
}

git --version || {
    mkdir -p /etc/portage/package.use
    grep 'dev-vcs/git' /etc/portage/package.use/dev-vcs \
        || tee -a /etc/portage/package.use/dev-vcs \
        <<< 'dev-vcs/git -pcre -perl -python -webdav'
    emerge -uDNvj dev-vcs/git --usepkg --getbinpkg --update
}

if [ -d /root/genboot ];
then
    (cd /root/genboot; git pull)
else
    git clone https://github.com/bencord0/genboot.git /root/genboot
fi
(cd /; patch -p0 -l -N < /root/genboot/user.eclass.patch) || true

cd genboot
bash stage-template.sh
bash build_stage3.sh
bash build_squashfs.sh
bash build_modules.sh
bash prepare_dracut.sh
bash build_initramfs.sh
bash build_vmlinuz.sh
bash pack_portdir.sh
